language: generic

compiler:
    - g++

sudo: required

dist: trusty

addons:
  apt:
    packages:
      - g++
      - gettext
      - intltool
      - libqt4-dev
      - autoconf
      - automake
      - libexiv2-dev
      - libalglib-dev
      - libboost-all-dev


before_script:
    - mkdir -p build
    - cd build
    - export PKG_CONFIG_PATH=/zyx/lib/pkgconfig:${PKG_CONFIG_PATH}
    - export LD_LIBRARY_PATH=/zyx/lib:${LD_LIBRARY_PATH}
    - git clone https://github.com/LibRaw/LibRaw.git
    - cd LibRaw
    - autoreconf --install
    #- automake --add-missing
    #- autoconf
    - pwd
    - ls
    - ./configure --prefix=/usr
    - make -j2
    - sudo make install
    - cd ..
    - cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr ..
    - make DESTDIR=$TRAVIS_BUILD_DIR/appdir -j2 install
    - cd ..

script:
    - bash appimage/appimage.sh
